server:
  port: 8080

spring:
  application:
    name: seckill-launcher
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: false
      config:
        server-addr: 127.0.0.1:8848
        enabled: false
        file-extension: yaml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckill-producer-group

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.reditickets.*.entity